### ISSUE TITLE
训练过程中精度无法提升

### ISSUE THREAD

**Issue by xxhaonan** [dexin-wang/AFFGA_Net_plgp#1]
我下载了PLGP数据集中的grasp
![image](https://github.com/dexin-wang/AFFGA_Net_plgp/assets/81416871/a8e0bb20-9696-47b3-b7de-9a6f2a77e802)
按照readme的方式创建了文件夹，并且能够训练，我将batchsize修改为8，其它参数不变，可是训练精度卡在了0.02无法提高，请问可能是什么原因造成的呐？
![image](https://github.com/dexin-wang/AFFGA_Net_plgp/assets/81416871/67733b67-b465-4268-9108-a9c6df5d9ec9)

**Comment by dexin-wang** [comment]
没遇到过，看一下训练日志

**Comment by xxhaonan** [comment]
别的图都挺正常，只有这个train_val_accuracy_tp一直在震荡
![image](https://github.com/dexin-wang/AFFGA_Net_plgp/assets/81416871/b33c8bc4-0b71-4f2a-9185-d3aaae4c343b)
![image](https://github.com/dexin-wang/AFFGA_Net_plgp/assets/81416871/f1055d31-b7e5-4e7c-a689-3e8a86764b51)

**Comment by dexin-wang** [comment]
图中的数据是正常的，精度包括test_accuracy_line和test_accuracy_tp，这两个都只是方便看训练进度，不作为方法性能的评判结果。测试方法性能要用仿真抓取benchmark: https://github.com/dexin-wang/ODG-Generation#3-benchmark.
